interfaces:
  leaf1:
    loopback: "10.2.1.1"
    int_numbered:
      swp1:
        ip_and_mask: "10.1.1.1/30"
      swp2:
        ip_and_mask: "10.1.1.5/30"
      swp3:
        ip_and_mask: "10.1.1.9/30"
      swp4:
        ip_and_mask: "10.1.1.13/30"
    bridges:
      br0:
        ip_and_mask: "10.4.1.1/25"
        members: ["swp30","swp31","swp32","swp33"]
      br1:
        ip_and_mask: "10.4.1.129/25"
        members: ["swp34","swp35","swp36","swp37"]
  leaf2:
    loopback: "10.2.1.2"
    int_numbered:
      swp1:
        ip_and_mask: "10.1.1.2/30"
      swp2:
        ip_and_mask: "10.1.1.6/30"
      swp3:
        ip_and_mask: "10.1.1.10/30"
      swp4:
        ip_and_mask: "10.1.1.14/30"
    bridges:
      br0:
        ip_and_mask: "10.4.2.1/25"
        members: ["swp30","swp31","swp32","swp33"]
      br1:
        ip_and_mask: "10.4.2.129/25"
        members: ["swp34","swp35","swp36","swp37"]

hostnetranges:
  - 10.4.0.0/16

bgp:
  leaf1:
    myasn: 65000
    peergroupv4:
      leaf2:
        peerasn: 65000
        peers: ["10.1.1.2","10.1.1.6","10.1.1.10","10.1.1.14"]
  leaf2:
    myasn: 65000
    peergroupv4:
      leaf1:
        peerasn: 65000
        peers: ["10.1.1.1","10.1.1.5","10.1.1.9","10.1.1.13"]
